### ISSUE TITLE
Define factsmisison ontology and adjust IRIs

### ISSUE THREAD

**Issue by retog** [factsmission/website#16]
We currently use properties like <http://factsmission.com/hasSideBar> and <http://factsmission.com/citation>, I suggest using the namespace "https://schema.factsmission.com" instead and provide RDFS or OWL descriptions of these terms

**Comment by retog** [comment]
@nleanba, could you have a look why https://schema.factsmission.com/citation is missing nodes? In Edge (no client-side rendering one sees 3 blank nodes, in Chrome only 1.

**Comment by nleanba** [comment]
> @nleanba, could you have a look why https://schema.factsmission.com/citation is missing nodes? In Edge (no client-side rendering one sees 3 blank nodes, in Chrome only 1.

This was a problem with the renderers and has now been resolved

**Comment by retog** [comment]
Thanks @nleanba!
